Hackathon.Avengers/Avengers.Mvc/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Avengers.Mvc.Controllers
{
    public class AdminController : Controller
    {
        public ActionResult ActivityDetail()
        {
            ViewBag.Message = "Your activity detail page.";

            return View();
        }
    }
}

Hackathon.Avengers/Avengers.Mvc/Controllers/AuditorController.cs
using Avengers.Mvc.Services;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using Avengers.Mvc.Models;
using WebGrease.Css.Extensions;

namespace Avengers.Mvc.Controllers
{
    public class AuditorController : Controller
    {
        ProvidersService _providerService;
        PatientsService _patientService;
        IEnumerable<Provider> _providers;
        IEnumerable<Patient> _patients;

        public AuditorController()
        {
            var client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:60225/api/");
            var clientWrapper = new HttpClientWrapper(client);
            _providerService = new ProvidersService(clientWrapper);
            _patientService = new PatientsService(clientWrapper);
        }

        public ActionResult Dashboard()
        {
            var viewModel = GetDashboardViewModel();
            ViewBag.Message = "Your contact page.";

            return View(viewModel);
        }

        private DashboardViewModel GetDashboardViewModel()
        {
            _providers = _providerService.GetProviders();
            _patients = _patientService.GetPatients();
            var dashboardEntities = new List<DashboardEntity>();

            _providers.ForEach(p => dashboardEntities.Add(new DashboardEntity { ID = p.ProviderID, FullName = $"{p.FirstName} {p.LastName}", Type = "provider", Entity = p }));
            _patients.ForEach(p => dashboardEntities.Add(new DashboardEntity { ID = p.Ssn, FullName = $"{p.FirstName} {p.LastName}", Type = "patient", Entity = p }));

            return new DashboardViewModel { Entities = dashboardEntities.OrderBy(x => x.FullName) };
        }

        [Route("/GetDetailPartialView/{id}/{type}")]
        public PartialViewResult GetDetailPartialView(string id, string type)
        {
            var entity = GetEntity(id, type);
            if (entity == null)
                return null;
            var partialName = type == "provider" ? "_ProviderDashboardDetailsPartial" : "_PatientDashboardDetailsPartial";
            return PartialView(partialName, entity);
        }

        private object GetEntity(string id, string type)
        {
            switch (type)
            {
                case "provider":
                    // This call takes FOREVERRRR
                    _providers = _providerService.GetProviders();
                    return _providerService.GetProvider(id, _providers);
                case "patient":
                    _patients = _patientService.GetPatients();
                    return _patientService.GetPatient(id, _patients);
                default:
                    return null;
            }
        }
    }
}

Hackathon.Avengers/Avengers.Mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Avengers.Mvc.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Login()
        {
            ViewBag.Message = "Your login page.";

            return View();
        }

        public ActionResult AdminLogin()
        {
            ViewBag.Message = "Your admin login page.";

            return View();
        }
    }
}

Hackathon.Avengers/Avengers.Mvc/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("FraudRx", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
        </div>
    </div>
</div>

<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Hackathon.Avengers/Avengers.Mvc/Views/Home/AdminLogin.cshtml
@{
    ViewBag.Title = "Admin Login";
}

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("FraudRx", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
        </div>
    </div>
</div>

<br/>
<h3>@ViewBag.Title</h3>
<br/>
<div class="container">

    <form class="form-signin">
        <!--<h2 class="form-signin-heading">Auditor Login</h2>-->
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="">
        <br/>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required="">
        <div class="checkbox">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <br/>
        <button class="btn btn-default" type="submit">@Html.ActionLink("Log In", "ActivityDetail", "Admin")</button>
    </form>

</div>

Hackathon.Avengers/Avengers.Mvc/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("FraudRx", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
        </div>
    </div>
</div>


<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Hackathon.Avengers/Avengers.Mvc/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("FraudRx", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
        </div>
    </div>
</div>

<div class="jumbotron">
    <h1>Opioid Fraud Detection Tool</h1>
    <p class="lead">Please sign in.</p>
    <p><button type="button" class="btn btn-default">@Html.ActionLink("Auditor Login >>", "Login", "Home")</button> <button type="button" class="btn btn-default">@Html.ActionLink("Administrator Login >>", "AdminLogin", "Home")</button></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            How to use the fraud detection tool.
        </p>
        <p><a class="btn btn-default" src="/Views/Home/About.cshtml">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Medicare Part D</h2>
        <p>See past Medicare Part D prescriber datasets.</p>
        <p><a class="btn btn-default" href="https://data.cms.gov/part-d-prescriber">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Opioid Crisis</h2>
        <p>See the latest news concerning the opioid crisis in America.</p>
        <p><a class="btn btn-default" href="https://www.google.com/search?q=opioid+epidemic+news&rlz=1C1GGRV_enUS764US764&source=lnms&tbm=nws&sa=X&ved=0ahUKEwivzcvXuoXbAhUK0VMKHcoBCv4Q_AUICigB&biw=1298&bih=582">Learn more &raquo;</a></p>
    </div>
    
</div>

Hackathon.Avengers/Avengers.Mvc/Views/Home/Login.cshtml
@{
    ViewBag.Title = "Auditor Login";
}

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("FraudRx", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
        </div>
    </div>
</div>

<br/>
<h3>@ViewBag.Title</h3>
<br/>
<div class="container">

    <form class="form-signin">
        <!--<h2 class="form-signin-heading">Auditor Login</h2>-->
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="">
        <br/>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required="">
        <div class="checkbox">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <br/>
        <button class="btn btn-default" type="submit">@Html.ActionLink("Log In", "Dashboard", "Auditor")</button>
    </form>

</div>